### ISSUE TITLE
Warning message every time i build the USB... 

### ISSUE THREAD

**Issue by Ezmoshow** [tabs-not-spaces/Intune.USB.Creator#8]
I am now getting a warning every time i try to build the USB.. just started happening a few days ago.. 

Grabbing PWSH 7..
VERBOSE: Destination: I:\scripts\pwsh
VERBOSE: About to download package from 'https://pscoretestdata.blob.core.windows.net/v7-1-0-daily-20200709/PowerShell-7.1.0-daily.20200709-win-x64.zip'
WARNING: Response status code does not indicate success: 404 (The specified resource does not exist.).

Seems like w/o this part working, the USB is a dud... 

Is this happening to anyone else?

any suggestions on a fix?

Thanks!

**Comment by Ezmoshow** [comment]
Looks like it just going out to grab the install-powershell.ps1 script and running the daily build from that.  I just had to manually pull that myself, and copied the bits over to the USB.  Got a functioning USB now!

**Comment by enroll-bacon** [comment]
Had the same error, installed the latest powershell build, then copied that to D:\Scripts\pwsh
USB works again now

**Comment by tabs-not-spaces** [comment]
this is happening because the script is pulling the daily build of PWSH7 which currently has the MSI pulled for build issues.

![image](https://user-images.githubusercontent.com/33951277/87308712-f4083e00-c55e-11ea-9fbe-58d8766b4b20.png)

Should be a simple fix - just omit the -Daily parameter from line 82 of Publish-ImageToUSB.ps1

https://github.com/tabs-not-spaces/Intune.USB.Creator/blob/931eb95e62c3690cb492330bd6d020d6e26cc52c/Intune.USB.Creator/Public/Publish-ImageToUSB.ps1#L82

Changes to:

``` PowerShell
. $env:Temp\install-powershell.ps1 -Destination "$($usb.drive):\scripts\pwsh" 
```

If anyone felt like making a contribution but didn't know where to start, this would be it.
